const container = document.querySelector('#container');
container.style.background = 'lightpink';
const content = document.createElement('div');
content.style.background = 'lightblue';
content.classList.add('content');
content.textContent = 'this is some text';
container.appendChild(content);
const p = document.createElement('p');
p.style.color = 'red';
content.classList.add('p');
p.textContent = "hey i'm red!";
container.appendChild(p);
const h3 = document.createElement('h3');
h3.style.color = 'blue';
content.classList.add('h3');
h3.textContent = "i'm a blue h3";
container.appendChild(h3);
const divElement = document.createElement("div");
divElement.style.border = "1px solid black";
const h1Element = document.createElement("h1");
h1Element.textContent = "hey i'm a div";
divElement.appendChild(h1Element);
const pElement = document.createElement("p");
pElement.textContent = "me too";
divElement.appendChild(pElement);
document.body.appendChild(divElement);
